version: "3.8"

services:
  php:
    build:
      context: ./..
      target: php_fpm_dev
    depends_on:
      - database
    restart: unless-stopped
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
  web:
    image: nginx:alpine
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev/nginx.conf:/etc/nginx/nginx.conf
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-simpleapi}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/data/postgres
    restart: unless-stopped
    networks:
      simple-api:

volumes:
  postgres:

networks:
  simple-api:
    name: test-toto
